account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

feed/urls.py
#앱 내의 urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.feed, name='feed'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('clearfeed/', views.clearfeed, name='clearfeed'),
    path('createcomment/<int:id>', views.createcomment, name='createcomment'),
]

picker/urls.py
#앱 내의 urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.result, name='result'),
    path('reservation', views.reservation, name='reservation'),
    path('change/', views.change, name='change'),
    path('fever/', views.fever, name='fever'),
    path('completion/<int:id>/', views.completion, name='completion'),
    path('delete/', views.delete, name="delete"),
]

randomproject/urls.py
from django.contrib import admin
from django.urls import path, include
import picker.views
import account.views
import feed.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('picker.urls')),
    path('account/', include('account.urls')),
    path('feed/', include('feed.urls')),
]

account/models.py
from django.db import models

# Create your models here.

feed/models.py
from django.db import models

# Create your models here.
class Feed(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

picker/models.py
from django.db import models

# Create your models here.
class Number(models.Model):
    number = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

class Reservation(models.Model):
    name = models.CharField(max_length=100)
    value = models.IntegerField(null=True, blank=True)
    status = models.BooleanField(null=True, blank=True, default=False)
    created_at = models.DateTimeField(auto_now_add=True)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'signup.html')
            except User.DoesNotExist:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                auth.login(request,user)
                return redirect('result')
        else:
            return render(request, 'signup.html')
    else:
        return render(request, 'signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('reservation')
        else:
            return render(request, 'login.html')
    return render(request, 'login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('result')
    return render(request, 'accounts/signup.html')

feed/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Feed, Comment

# Create your views here.
def feed(request):
    if request.method == 'POST':
        name = request.POST['name']
        content = request.POST['content']
        feed = Feed.objects.create(name=name, content=content)
        return redirect('feed')
    else:
        feeds = Feed.objects.order_by('-created_at')
        return render(request, 'feed.html', {'feeds': feeds})

def detail(request, id):
    feed = get_object_or_404(Feed, pk=id)
    return render(request, 'detail.html', {'feed': feed})

def clearfeed(request):
    feeds = Feed.objects.all()
    feeds.delete()
    return redirect('feed')

def createcomment(request, id):
    feed = get_object_or_404(Feed, pk=id)
    if request.method=='POST':
        name=request.POST['name']
        content=request.POST['content']
        comment = Comment.objects.create(name=name, content=content, feed=feed)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

picker/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Number, Reservation

# Create your views here.
def result(request):
    num = Number.objects.last()
    return render(request, 'result.html', {'num': num})

def reservation(request):
    if request.method == 'POST':
        name = request.POST['name']
        value = Number.objects.last().number
        reservation = Reservation.objects.create(name=name, value=value)
        return redirect('reservation')
    else:
        reservations = Reservation.objects.all()
        return render(request, 'reservation.html', {'reservations': reservations})

def completion(request, id):
    reservation = get_object_or_404(Reservation, pk=id)
    if reservation.status == False:
        reservation.status = True
    else:
        reservation.status = False
    reservation.save()
    return redirect('reservation')

def delete(request):
    reservations = Reservation.objects.filter(status=True)
    reservations.delete()
    return redirect('reservation')

def change(request):
    import random
    
    ran_num = random.randrange(1, 11)
    if ran_num == 1:
        num = 1
    elif ran_num in range(2,4): # 2, 3
        num = 2
    elif ran_num in range(4, 8): # 4, 5, 6, 7
        num = 3
    elif ran_num in range(9, 10): # 8, 9
        num = 4
    else: # 10
        num = 5
    numbers = Number.objects.all()
    numbers.delete()
    Number.objects.create(number=num)
    return redirect('result')

def fever(request):
    import random

    ran_num = random.randrange(1, 15)
    if ran_num == 1:
        num = 1
    elif ran_num in range(2, 4): # 2, 3
        num = 2
    elif ran_num in range(4, 6): # 4, 5
        num = 3
    elif ran_num in range(6, 8): # 6, 7
        num = 4
    elif ran_num == 8:
        num = 5
    elif ran_num in range(9, 12): # 9, 10, 11
        num = 0
    else: # 12, 13, 14
        num = 6
    numbers = Number.objects.all()
    numbers.delete()
    Number.objects.create(number=num)
    return redirect('result')

def generate():
    import random
    change = random.randrange(1, 10)
    if change == 1:
        pass
    elif change == 2:
        pass
    elif change == 3:
        pass
    else:
        ran_num = random.randrange(1, 11)
        if ran_num == 1:
            num = 1
        elif ran_num in range(2,4): # 2, 3
            num = 2
        elif ran_num in range(4, 8): # 4, 5, 6, 7
            num = 3
        elif ran_num in range(9, 10): # 8, 9
            num = 4
        else: # 10
            num = 5
        numbers = Number.objects.all()
        numbers.delete()
        Number.objects.create(number=num)
        return redirect('result')

account/templates/login.html
<body>
    {% extends 'base.html' %}
    {% block content %}
    <div class="card border-primary my-5 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-header"><p class='text-center' style="font-size: 5rem; font-family: 'Press Start 2P', cursive;">* LOGIN *</p></div>
        <div class="card-body text-primary">
            <form method='POST' action="{% url 'login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1" style="font-size: 4rem; font-family: 'Do Hyeon', sans-serif;">아이디</label>
                    <input name='username' class="form-control form-control-lg" style="font-size: 4rem; font-family: 'Do Hyeon', sans-serif;" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" style="font-size: 4rem; font-family: 'Do Hyeon', sans-serif;">비밀번호</label>
                    <input input name='password' type="password" class="form-control form-control-lg" style="font-size: 4rem; font-family: 'Do Hyeon', sans-serif;" id="exampleInputPassword1">
                </div>
                <button type="submit" class="btn btn-lg btn-primary btn-block" style="font-size: 3rem; font-family: 'Do Hyeon', sans-serif;">로그인</button>
            </form>
            
        </div>
    </div>
    {% endblock %}
</body>

account/templates/signup.html
<form method='POST' action="{% url 'signup' %}">
    {% csrf_token %}
    username:<input name='username'/><br/>
    password1:<input name='password1' type='password'><br/>
    password2:<input name='password2' type='password'><br/>
    <input type='submit' value='제출'/>
</form>

feed/templates/detail.html
<body>
    {% extends 'base.html' %}
    {% block content %}

    <div class="mx-auto mt-5" style="max-width: 80%;">
        <a href="{% url 'feed' %}" class="mx-auto" style="font-size: 2.5rem;">뒤로가기</a>
    </div>

    <div class="card border-primary my-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <p style="font-size: 3rem; color: black;">작성자 : {{feed.name}}</p>
            <p style="font-size: 2rem; color: grey">{{feed.created_at|date:"n월 j일 H시 i분"}}</p>
            <hr/>
            <p style="font-size: 2.5rem; color: black;">{{feed.content}}</p>
        </div>
    </div>
    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <form action="{% url 'createcomment' feed.id %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-3">
                        <input type="text" name="name" class="form-control" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;" placeholder="이름">
                    </div>
                    <div class="col">
                        <input type="text" name="content" class="form-control" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;" placeholder="댓글내용">
                    </div>
                    <div class="col-3">
                        <button type="submit" class="btn btn-primary btn-block" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;">등록</button>
                    </div>
                </div>
            </form>
            {% for comment in feed.comment_set.all %}
                <p style="font-size: 2.5rem; color: black;">{{comment.name}} : {{comment.content}}</p>
                <p style="font-size: 2rem; color: grey">{{comment.created_at|date:"n월 j일 H시 i분"}}</p>
            {% endfor %}
        </div>
        
    </div>
    {% endblock %}
</body>

feed/templates/feed.html
<body>
    {% extends 'base.html' %}
    {% block content %}
    <p class='text-center mt-5' style="font-family: 'Black Han Sans', sans-serif; font-size: 5rem;">피 드</p>
    
    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <form action="{% url 'feed' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="name" class="form-control mb-3" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;" placeholder="이름">
                <textarea name="content" class="form-control mb-3" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;" placeholder="내용"></textarea>
                <button type="submit" class="btn btn-primary btn-block" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;">등록</button>
            </form>
        </div>
    </div>

    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <table class="table" style="font-size: 2.5rem;">
            {% if user.is_authenticated %}
                    <a href="{% url 'clearfeed' %}" class="btn btn-secondary btn-block" style="font-size: 3rem; color: white;">전체 삭제하기</a>
                {% endif %}
                <thead>
                    <tr>
                        <th scope="col">이름</th>
                        <th scope="col" style="width: 80%;">내용</th>
                    </tr>
                </thead>
                <tbody>
                    {% for f in feeds %}
                    <tr>
                        <th scope="row">{{f.name}}</th>
                        <td><a href="{% url 'detail' f.id %}">{{f.content}} ..({{f.comment_set.count}})</a></td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
                </table>    
        </div>
    </div>
    {% endblock %}
</body>

picker/templates/reservation.html
<body>
    {% extends 'base.html' %}
    {% block content %}
    <p class='text-center mt-5' style="font-family: 'Black Han Sans', sans-serif; font-size: 5rem;">코인 판매 예약</p>
    
    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <form action="{% url 'reservation' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <input type="text" name="name" class="form-control" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;" placeholder="이름">
                    </div>
                    <div class="col-3">
                        <button type="submit" class="btn btn-primary btn-block" style="font-family: 'Do Hyeon', sans-serif; font-size: 3rem;">예약</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-body text-primary">
            <table class="table" style="font-size: 2.5rem;">
            {% if user.is_authenticated %}
                    <a href="{% url 'delete' %}" class="btn btn-secondary btn-block" style="font-size: 3rem; color: white;">완료 목록 삭제하기</a>
                {% endif %}
                <thead>
                    <tr>
                    <th scope="col">이름</th>
                    <th scope="col">예약 날짜</th>
                    <th scope="col">코인 가격</th>
                    <th scope="col">처리 여부</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">(예)눈송</th>
                        <td>9월 5일</td>
                        <td>3</td>
                        <td>완료!</td>
                    </tr>
                    {% for r in reservations %}
                    <tr>
                        <th scope="row">{{r.name}}</th>
                        <td>{{r.created_at|date:"n월 j일"}}</td>
                        <td>{{r.value}}</td>
                        <td>
                            {% if user.is_authenticated %}
                                {% if r.status == False %}
                                    <a href="{% url 'completion' r.id %}" class="btn btn-info" style="font-size: 2rem;">완료하기</a>
                                {% else %}
                                    <a href="{% url 'completion' r.id %}" class="btn btn-warning" style="font-size: 2rem;">완료취소</a>
                                {% endif %}
                            {% else %}
                                {% if r.status == False %}
                                    대기중
                                {% else %}
                                    완료!
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
                </table>    
        </div>
    </div>
    {% endblock %}
</body>

picker/templates/result.html
<body>
    {% extends 'base.html' %}
    {% block content %}
    <p class='text-center mt-5' style="font-family: 'Black Han Sans', sans-serif; font-size: 4rem;">코인 시세 확인하기</p>
    <div class="card border-primary mb-3 mx-auto" style="max-width: 80%; border-width: 5px;">
        <div class="card-header"><p class='text-center' style="font-size: 5rem; font-family: 'Press Start 2P', cursive;">* COIN *</p></div>
        <div class="card-body text-primary">
            <p class="card-title text-center my-5 py-5" style="font-size: 15rem; font-family: 'Black Han Sans', sans-serif;">{{num.number}}개</p>
            <p class="card-text" style="font-size: 2rem; font-family: 'Black Han Sans', sans-serif;">{{num.created_at|date:"n월 j일 h시 i분 기준"}}</p>
            <p class="card-text" style="font-size: 2rem; font-family: 'Black Han Sans', sans-serif;">
                {% if user.is_authenticated %}
                    <a href="{% url 'change' %}">주가 바꾸기</a><br/>
                    <a href="{% url 'fever' %}">피버타임</a>
                {% endif %}
            </p>
            
        </div>
    </div>
    {% endblock %}
</body>

randomproject/templates/base.html
<head>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>


<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'result' %}" style="font-family: 'Do Hyeon', sans-serif; font-size: 5rem;">눈송마을</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="font-size: 3rem;"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav" style="font-size: 3rem; font-family: 'Do Hyeon', sans-serif;">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'result' %}">코인 시세 확인</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'reservation' %}">코인 판매 예약</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'feed' %}">피드</a>
            </li>
            <li class="nav-item active">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
                    <form id="logout" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %} <input type="hidden" />
                    </form>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}">GM 로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}